Repository ThioJoe/YT-Spammer-Purge, pull requests merged in 2022-02, with the labels that each got.

#492 Update dockerfile to slim base image
  Dockerfile
Labels: Can Someone Who Knows About This Check It

#356 Linux Auto-Updater
  Scripts/files.py
Labels: in-review, Can Someone Who Knows About This Check It

#510 Add Option to disable Colors
  README.md
  Scripts/shared_imports.py
  Scripts/validation.py
  YTSpammerPurge.py
  assets/default_config.ini
Labels: will-probably-add

#424 REPOST Detection - detect and delete comments that aren't unique
  Scripts/logging.py
  Scripts/operations.py
  YTSpammerPurge.py
  assets/default_config.ini
Labels: in-progress
